site_name: containertips.dev

nav:
    - Home: 'index.md'
    - Docker:
        - docker/index.md
    - Kubernetes:
        - kubernetes/index.md
        - Helm:
            - Intro: kubernetes/helm/index.md
            - 1. Comenzando: kubernetes/helm/1.start.md
            - 2. Charts: kubernetes/helm/2.charts.md
            - 3. Subcharts: kubernetes/helm/3.subcharts.md
            - 4. Templates: kubernetes/helm/3.templates.md
    - Devops:
        - devops/index.md
    - About: 'about.md'
    - Contact: 'contact.md'



site_author: Marcos Cano
site_description: All about Docker, K8 and Containers in general

#google_analytics: ['UA-36723568-3', 'mkdocs.org']

repo_name: containertips.dev
repo_url: https://github.com/jmarcos-cano/containertips.dev/src
edit_uri: ""

theme:
  name: material
  palette:
    primary: "blue grey"
    accent: 'deep orange'
  logo: 'assets/images/vessel.png'
  font:
    text: 'Space Mono'
    code: 'Inconsolata'
  language: 'en'
  favicon: 'assets/images/favicon.ico'
  #include_sidebar: True
  feature:
    tabs: true


extra:
  manifest: 'manifest.webmanifest'
  search:
    language: 'en, es'
  social:
    - type: 'github'
      link: 'https://github.com/jmarcos-cano/containertips.dev/'
    - type: 'twitter'
      link: 'https://twitter.com/Marcos_Kno'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/marcos-cano-804a1787/'

plugins:
  - search
  #- macros
  #- markdownextradata: {}
markdown_extensions:
  - codehilite:
        guess_lang: False
        use_pygments: True
        noclasses: True
        pygments_style: monokai
  - footnotes
  #- admonition
  - meta
  - toc:
        permalink: true
  - pymdownx.extra
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.smartsymbols

extra_css:
    - assets/css/extra.css
    - assets/css/contact_form.css

use_directory_urls: true